---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-flask-app
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-flask-app
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-flask-app
    spec:
      containers:
        - name: {{ .Chart.Name }}-flask-app
          image: {{ .Values.image.repository }}
          ports:
            - containerPort: {{ .Values.service.targetPort }}
          volumeMounts:
            - name: config-volume
              mountPath: /app/templates
      volumes:
        - name: config-volume
          configMap:
            name: {{ .Release.Name }}-flask-html-config
