# # Apply Application Pod for argo cd to "argocd" NameSpace to deploy to "app"

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: "argo-application"
spec:
  destination:
    namespace: app
    server: "https://kubernetes.default.svc"
  source:
    path: "kubernetes"
    repoURL: "https://github.com/Joska99/Targil1090.git"
    targetRevision: HEAD
  project: "default"
