# Apply Application Pod for argo cd to "app" NameSpace to deploy

apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: argo-application
spec:
  generators:
    - clusters: {}
  template:
    metadata:
      name: argo-application
    spec:
      project: "default"
      source:
        repoURL: https://github.com/Joska99/Targil1090.git
        targetRevision: HEAD
        path: kubernetes
      destination:
        server: https://kubernetes.default.svc
        namespace: app
