apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
        - name: flask-app
          image: joska99/flask-app:0.0.1
          ports:
            - containerPort: 5000
          volumeMounts:
            - name: config-volume
              mountPath: /app/templates
      volumes:
        - name: config-volume
          configMap:
            name: flask-html-config
